### ISSUE TITLE
PN-23 scope has no reticle in certain cases

### ISSUE THREAD

**Issue by napo1emon** [andtheherois/3DSS-For-BAS22#1]
Problem occurs on rifles that allow for installing the PN-23 in front of their fixed scope (like the G28). The night vision works but there's no reticle.

![PN-23 off](https://github.com/user-attachments/assets/f6a1bb61-6874-4ea7-bb3b-4f660fb0cfa6)
![PN-23 on](https://github.com/user-attachments/assets/c6c3d5bf-7592-4799-bbc8-64e232b4568a)

**Comment by andtheherois** [comment]
no other report of this. most likely user error

**Comment by napo1emon** [comment]
Turns out I didn't have the newest version of 3DSS. My bad.
