### ISSUE TITLE
wpn_kar98_retrotac scope not working

### ISSUE THREAD

**Issue by napo1emon** [andtheherois/3DSS-For-BAS22#2]
wpn_kar98_retrotac scope is not working; switching modes only gives black or red circle

![AnomalyDX11AVX 2024-10-10 22-13-34](https://github.com/user-attachments/assets/ad54fdaa-0139-4248-b400-c10ac4756339)
![AnomalyDX11AVX 2024-10-10 22-13-37](https://github.com/user-attachments/assets/5ed0c28a-ea6f-46b2-a9fb-30c2c3b1a761)

**Comment by andtheherois** [comment]
is your 3dss file up to date?

**Comment by napo1emon** [comment]
Sorry, it wasn't. My bad.
